# Generated by Django 4.2.7 on 2024-01-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeMaster', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
